name: WormholeXTreme
main: com.wormhole_xtreme.WormholeXTreme
version: 0.755
author: By Lologarithm & alron
description: >
             Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC,
             Iris, configurable Wormhole materials, and much much more.
             
commands:
   dial:
     description: Dial a remote Stargate, unlock IDC with optional password.
     usage: |
            /<command> <stargate> [IDC]
            Example: /<command> <GateName> 
                     - Dial Stargate.
            Example: /<command> <GateName> [GatePassword] 
                     - Dial Iris locked Stargate.
            
   wormhole:
     description: Wormhole related commands. Mostly configuration.
     usage: |
            /<command> <commandtype> [ARG1] [ARG2]
            Example: /<command> complete <GateName> [IDC] 
                     - IDC password optional.
            Example: /<command> compass 
                     - Use compass to target Nearest Stargate.
            Example: /<command> remove <GateName> [-all] 
                     - Specify all to destroy materials.

   wxlist:
     description: List all built Stargates.
     usage: |
            /<command> - List all active stargates.
            
   wxbuild:
     description: Automatically Build Stargate.
     usage: |
            /<command> <GateShape>
            - After placing a DHD with a button (and sign if wanted) running this command then pressing the button will cause the specified stargate to be built.
            
   wxremove:
     description: Remove a stargate, optionally destroy its blocks.
     usage: |
            /<command> <GateName> [-all]
            Example: /<command> testgate -all
            - -all destroys gate blocks.
            
