name: WormholeXTreme
main: com.wormhole_xtreme.WormholeXTreme
version: 0.755
author: By Lologarithm & alron
description: >
             Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC,
             Iris, configurable Wormhole materials, and much much more.
             
commands:
   dial:
     description: Dial a remote Stargate, unlock IDC with optional password.
     usage: |
            /<command> <StarGate> [IDC]
            <stargate> The StarGate to dial.
            [IDC] Use optional password to open remote Iris.
                     
            
   wormhole:
     description: Wormhole related commands. Mostly configuration.
     usage: |
            /<command> <commandtype> [ARG1] [ARG2]
            Example: /<command> complete <GateName> [IDC] 
                     - [IDC] password optional.
            Example: /<command> compass 
                     - Use compass to target Nearest Stargate.
            Example: /<command> remove <GateName> [-all] 
                     - [-all] Specify to destroy materials.

   wxlist:
     description: List all Stargates.
     usage: |
            /<command> - List all Stargates.
            
   wxbuild:
     description: Automatically Build Stargate.
     usage: |
            /<command> <GateShape>
            <GateShape> The GateShape to build.
            After placing a DHD with a button (and sign if wanted) running this command then pressing the button will cause the specified <GateShape> to be built.
            
   wxremove:
     description: Remove a stargate, optionally destroy its blocks.
     usage: |
            /<command> <GateName> [-all]
            <GateName> The GateName to remove.
            [-all] destroys gate blocks too.